apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calc-web
  template:
    metadata:
      labels:
        app: calc-web
    spec:
      containers:
      - name: calc-web
        image: ${IMAGE_URI}
        ports:
        - containerPort: 5000
 
